name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - name: Run build script (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: build.bat
      - name: Run build script (Linux)
        if: runner.os != 'Windows'
        run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: executables-${{ matrix.os }}
          path: dist/*
